<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="3" hostname="BSRUTHI-IN" name="testcases.TC004_CreateApplicationInstance" tests="4" failures="0" timestamp="23 May 2019 06:44:08 GMT" time="88.253" errors="1">
  <testcase name="soa" time="0.000" classname="testcases.TC004_CreateApplicationInstance">
    <skipped/>
  </testcase> <!-- soa -->
  <testcase name="beforeMethod" time="88.253" classname="testcases.TC004_CreateApplicationInstance">
    <error type="java.lang.NoSuchMethodError" message="com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;J)V">
      <![CDATA[java.lang.NoSuchMethodError: com.google.common.base.Preconditions.checkArgument(ZLjava/lang/String;J)V
	at org.openqa.selenium.support.ui.Duration.<init>(Duration.java:41)
	at org.openqa.selenium.support.ui.FluentWait.<clinit>(FluentWait.java:72)
	at wrappers.GenericWrappers.startApp(GenericWrappers.java:114)
	at wrappers.ssdSandbox.beforeMethod(ssdSandbox.java:39)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:108)
	at org.testng.internal.Invoker.invokeConfigurationMethod(Invoker.java:523)
	at org.testng.internal.Invoker.invokeConfigurations(Invoker.java:224)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:599)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:869)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1193)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:126)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
	at org.testng.TestRunner.privateRun(TestRunner.java:744)
	at org.testng.TestRunner.run(TestRunner.java:602)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:380)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:375)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:340)
	at org.testng.SuiteRunner.run(SuiteRunner.java:289)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1301)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1226)
	at org.testng.TestNG.runSuites(TestNG.java:1144)
	at org.testng.TestNG.run(TestNG.java:1115)
	at testcases.MainClass.main(MainClass.java:16)
]]>
    </error>
  </testcase> <!-- beforeMethod -->
  <testcase name="testCreateSandBox" time="0.000" classname="testcases.TC004_CreateApplicationInstance">
    <skipped/>
  </testcase> <!-- testCreateSandBox -->
  <testcase name="validation" time="0.000" classname="testcases.TC004_CreateApplicationInstance">
    <skipped/>
  </testcase> <!-- validation -->
</testsuite> <!-- testcases.TC004_CreateApplicationInstance -->
